apiVersion: apps/v1
kind: Deployment
metadata:
  name: gymlife-deployment
  labels:
    app: gymlife
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gymlife
  template:
    metadata:
      labels:
        app: gymlife
    spec:
      containers:
        - name: gymlife-con
          image: quanghuyle3/gymlife-backend:2.0-url
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
            - name: MYSQL_URL
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: mysql-url
---
apiVersion: v1
kind: Service
metadata:
  name: gymlife-service
spec:
  # type: NodePort
  type: LoadBalancer
  selector:
    app: gymlife
  ports:
    - protocol: TCP
      # port: 8080
      port: 80
      targetPort: 8080
      # nodePort: 30100
